spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_robot
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format-sql: true
      database-platform: org.hibernate.dialect.PostgresQLDialect
application:
  security:
    jwt:
      secret-key: 73427a000a639788545c12b46128f64cb098b06f1bb601550fb4613bf8072714
      expiration: 86400000
      refresh-token:
       expiration: 604800000